package com.example.votingSystem.enums;

public enum ErrorCodes {
    INVALID_AUTHENTICATION_TYPE,
    USER_NOT_FOUND,
    INVALID_PAYLOAD,
    INVALID_CREDENTIAL,
    ELECTION_NOT_FOUND,
    NO_SEAT_AVAILABLE,
    DATE_EXPIRED,
    ALREADY_ENROLLED,
    INVALID_CATEGORY,
    NO_DATA_FOUND,
    INVALID_DATE_RANGE,
    INVALID_MOBILE,
    NOT_AUTHORISED
}
